# secrets.toml

OPENAI_API_KEY="sk-LNj0pewWtL4MzGmAWMEhe8100D-L0wr4-4mdFtPhCYT3BlbkFJwnXXfUIsPRGNY-zK45YfRzVvrL_R3UBv7NBCdCr_UA"
OpenAI_key="sk-LNj0pewWtL4MzGmAWMEhe8100D-L0wr4-4mdFtPhCYT3BlbkFJwnXXfUIsPRGNY-zK45YfRzVvrL_R3UBv7NBCdCr_UA"
openai_api_key = "sk-LNj0pewWtL4MzGmAWMEhe8100D-L0wr4-4mdFtPhCYT3BlbkFJwnXXfUIsPRGNY-zK45YfRzVvrL_R3UBv7NBCdCr_UA"

[passwords]
# Follow the rule: username = "password"
alice_foo = "streamlit123"
bob_bar = "mycrazypw"
varun_menon = "cofounder"
abhishek_mishra = "cofounder"
user = "password"
ycombinator = "password"
preethi = "password"