# secrets.toml

<<<<<<< HEAD
=======
OPENAI_API_KEY="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"
OpenAI_key="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"
openai_api_key = "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"

>>>>>>> parent of 14f8c61 (Update secrets.toml)
[passwords]
# Follow the rule: username = "password"
alice_foo = "streamlit123"
bob_bar = "mycrazypw"
varun_menon = "cofounder"
abhishek_mishra = "cofounder"
user = "password"
ycombinator = "password"
preethi = "password"