# secrets.toml
.env

[passwords]
# Follow the rule: username = "password"
alice_foo = "streamlit123"
bob_bar = "mycrazypw"
varun_menon = "cofounder"
abhishek_mishra = "cofounder"
ycombinator = "password"
preethi = "password"