# secrets.toml

OpenAI_key = "sk-proj-qtpho349zVsagqVHHYgPT3BlbkFJ7Ifxa7jD4tszGsRvBu2z"
[passwords]
# Follow the rule: username = "password"
alice_foo = "streamlit123"
bob_bar = "mycrazypw"
varun_menon = "cofounder"
abhishek_mishra = "cofounder"