# secrets.toml

OPENAI_API_KEY="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"
OpenAI_key="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"
openai_api_key = "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"

[passwords]
# Follow the rule: username = "password"
alice_foo = "streamlit123"
bob_bar = "mycrazypw"
varun_menon = "cofounder"
abhishek_mishra = "cofounder"
user = "password"
ycombinator = "password"
preethi = "password"