# secrets.toml
.env

OPENAI_API_KEY = "sk-proj-oYan0y73XX5ML6Xh5HF9T3BlbkFJU8pI5FlYdBBm1RAwXT3d"

[passwords]
# Follow the rule: username = "password"
alice_foo = "streamlit123"
bob_bar = "mycrazypw"
varun_menon = "cofounder"
abhishek_mishra = "cofounder"
user = "password"
ycombinator = "password"
preethi = "password"